version: '3.7'

services:
  chromadb:
    image: chromadb/chroma
    ports:
      - '1902:8000'
    volumes:
      - ../chroma-data:/data
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=1902

volumes:
  chroma_data:
